/* icons.h - GENERATED by tools/gen_icons.py from the assets/icons PNGs.
 * Do not edit by hand; re-run the script after changing the art. */
#ifndef POCKET_TANK_ICONS_H
#define POCKET_TANK_ICONS_H
#include <stdint.h>

typedef struct { uint8_t w, h; const uint16_t *rgb; const uint8_t *a; } icon_t;

extern const icon_t icon_bold;
extern const icon_t icon_cautious;
extern const icon_t icon_curiosity;
extern const icon_t icon_curious;
extern const icon_t icon_energy;
extern const icon_t icon_hunger;
extern const icon_t icon_shy;
extern const icon_t icon_social;
extern const icon_t icon_solo;
extern const icon_t icon_stress;
extern const icon_t icon_trust;
extern const icon_t icon_unknown_16;
extern const icon_t icon_unknown_24;
extern const icon_t icon_ms_first_bubbles;
extern const icon_t icon_ms_first_dart;
extern const icon_t icon_ms_first_feeding;
extern const icon_t icon_ms_first_follow;
extern const icon_t icon_ms_first_glass_cleaning;
extern const icon_t icon_ms_first_hold_approach;
extern const icon_t icon_ms_first_meal;
extern const icon_t icon_ms_first_play_session;
extern const icon_t icon_ms_first_quiet_night;
extern const icon_t icon_ms_first_reef;
extern const icon_t icon_ms_first_trimming;
extern const icon_t icon_ms_tank_changed_someone;

#endif
